'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
'
Namespace WebReference
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AutorizadorSoap", [Namespace]:="http://tempuri.org/SASSAutorizadorWEB/Autorizador")>  _
    Public Class Autorizador
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://192.168.0.130/sassautorizadorweb/autorizador.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SASSAutorizadorWEB/Autorizador/Autoriza", RequestNamespace:="http://tempuri.org/SASSAutorizadorWEB/Autorizador", ResponseNamespace:="http://tempuri.org/SASSAutorizadorWEB/Autorizador", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Autoriza(ByVal codTransacao As Integer, ByVal Cartao As String, ByVal codPrestador As Integer, ByVal codSolicitante As Integer, ByVal codEspecialidade As Integer, ByVal codLocal As Integer, ByVal viaCartao As Integer, ByVal ValidadeCartao As String, ByVal Servicos As String, ByVal codCID As String, ByVal nomeAtendente As String, ByVal Prototipo As Boolean) As String
            Dim results() As Object = Me.Invoke("Autoriza", New Object() {codTransacao, Cartao, codPrestador, codSolicitante, codEspecialidade, codLocal, viaCartao, ValidadeCartao, Servicos, codCID, nomeAtendente, Prototipo})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginAutoriza(ByVal codTransacao As Integer, ByVal Cartao As String, ByVal codPrestador As Integer, ByVal codSolicitante As Integer, ByVal codEspecialidade As Integer, ByVal codLocal As Integer, ByVal viaCartao As Integer, ByVal ValidadeCartao As String, ByVal Servicos As String, ByVal codCID As String, ByVal nomeAtendente As String, ByVal Prototipo As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Autoriza", New Object() {codTransacao, Cartao, codPrestador, codSolicitante, codEspecialidade, codLocal, viaCartao, ValidadeCartao, Servicos, codCID, nomeAtendente, Prototipo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAutoriza(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
