'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
'
Namespace WebReference
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AutorizadorSoap", [Namespace]:="http://tempuri.org/SASSAutorizadorWEB/Autorizador")>  _
    Partial Public Class Autorizador
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private AutorizaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://192.168.0.130/sassautorizadorweb/autorizador.asmx"
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event AutorizaCompleted As AutorizaCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SASSAutorizadorWEB/Autorizador/Autoriza", RequestNamespace:="http://tempuri.org/SASSAutorizadorWEB/Autorizador", ResponseNamespace:="http://tempuri.org/SASSAutorizadorWEB/Autorizador", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Autoriza(ByVal codTransacao As Integer, ByVal Cartao As String, ByVal codPrestador As Integer, ByVal codSolicitante As Integer, ByVal codEspecialidade As Integer, ByVal codLocal As Integer, ByVal viaCartao As Integer, ByVal ValidadeCartao As String, ByVal Servicos As String, ByVal codCID As String, ByVal nomeAtendente As String, ByVal Prototipo As Boolean) As String
            Dim results() As Object = Me.Invoke("Autoriza", New Object() {codTransacao, Cartao, codPrestador, codSolicitante, codEspecialidade, codLocal, viaCartao, ValidadeCartao, Servicos, codCID, nomeAtendente, Prototipo})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginAutoriza(ByVal codTransacao As Integer, ByVal Cartao As String, ByVal codPrestador As Integer, ByVal codSolicitante As Integer, ByVal codEspecialidade As Integer, ByVal codLocal As Integer, ByVal viaCartao As Integer, ByVal ValidadeCartao As String, ByVal Servicos As String, ByVal codCID As String, ByVal nomeAtendente As String, ByVal Prototipo As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Autoriza", New Object() {codTransacao, Cartao, codPrestador, codSolicitante, codEspecialidade, codLocal, viaCartao, ValidadeCartao, Servicos, codCID, nomeAtendente, Prototipo}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndAutoriza(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AutorizaAsync(ByVal codTransacao As Integer, ByVal Cartao As String, ByVal codPrestador As Integer, ByVal codSolicitante As Integer, ByVal codEspecialidade As Integer, ByVal codLocal As Integer, ByVal viaCartao As Integer, ByVal ValidadeCartao As String, ByVal Servicos As String, ByVal codCID As String, ByVal nomeAtendente As String, ByVal Prototipo As Boolean)
            Me.AutorizaAsync(codTransacao, Cartao, codPrestador, codSolicitante, codEspecialidade, codLocal, viaCartao, ValidadeCartao, Servicos, codCID, nomeAtendente, Prototipo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AutorizaAsync(ByVal codTransacao As Integer, ByVal Cartao As String, ByVal codPrestador As Integer, ByVal codSolicitante As Integer, ByVal codEspecialidade As Integer, ByVal codLocal As Integer, ByVal viaCartao As Integer, ByVal ValidadeCartao As String, ByVal Servicos As String, ByVal codCID As String, ByVal nomeAtendente As String, ByVal Prototipo As Boolean, ByVal userState As Object)
            If (Me.AutorizaOperationCompleted Is Nothing) Then
                Me.AutorizaOperationCompleted = AddressOf Me.OnAutorizaOperationCompleted
            End If
            Me.InvokeAsync("Autoriza", New Object() {codTransacao, Cartao, codPrestador, codSolicitante, codEspecialidade, codLocal, viaCartao, ValidadeCartao, Servicos, codCID, nomeAtendente, Prototipo}, Me.AutorizaOperationCompleted, userState)
        End Sub
        
        Private Sub OnAutorizaOperationCompleted(ByVal arg As Object)
            If (Not (Me.AutorizaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AutorizaCompleted(Me, New AutorizaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub AutorizaCompletedEventHandler(ByVal sender As Object, ByVal e As AutorizaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AutorizaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
